# Generated by Django 2.2.6 on 2019-10-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('textinside', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('pubdate', models.DateField()),
            ],
        ),
    ]
